import '@/scss/reset.scss'
import '@/scss/base.scss'

import '@/components/button/button.scss'
import '@/components/input/input.scss'
import '@/components/header/header.scss'
import '@/components/menu-button/menu-button.scss'
import '@/components/title/title.scss'
import '@/components/modal/modal.scss'
import '@/components/form/form.scss'
import '@/components/table-of-contents/table-of-contents.scss'
import '@/components/post-card/post-card.scss'
import '@/components/blog-filters/blog-filters.scss'
import '@/components/footer/footer.scss'

import '@/blocks/metrics/metrics.scss'
import '@/blocks/home/home.scss'
import '@/blocks/about/about.scss'
import '@/blocks/blog/blog.scss'
import '@/blocks/article/article.scss'
import '@/blocks/service/service.scss'

import '@/blocks/warehouse/warehouse.scss'

import '@/blocks/certified/certified.scss'

import '@/blocks/regs/regs.scss'
import '@/blocks/sla/sla.scss'

import '@/blocks/training/training.scss'

import '@/blocks/support/support.scss'
import '@/blocks/advantages/advantages.scss'
import '@/blocks/scheme/scheme.scss'
import '@/blocks/eco/eco.scss'
import '@/blocks/formats/formats.scss'
import '@/blocks/tech/tech.scss'
import '@/blocks/app-download/app-download.scss'
import '@/blocks/tehplatforma/tehplatforma.scss'
import '@/blocks/apps/apps.scss'
import '@/blocks/intl/intl.scss'
import '@/blocks/team/team.scss'
import '@/blocks/network/network.scss'
import '@/blocks/bento/bento.scss'
import '@/blocks/features/features.scss'
import '@/blocks/text-block/text-block.scss'
import '@/blocks/values/values.scss'
import '@/blocks/goal/goal.scss'
import '@/blocks/erp/erp.scss'
import '@/blocks/demo/demo.scss'

import '@/components/header/header.js'
import '@/components/modal/modal.js'
import '@/components/table-of-contents/table-of-contents.js'
import '@/components/blog-filters/blog-filters.js'
import '@/components/phone-mask/phone-mask.js'
import '@/blocks/tehplatforma/tehplatforma.js'
